{
 "title": "IPMI Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1s,5s,1m,5m,10m,30m,1h,3h,6h,12h,1d,2d,3d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(ipmi_temperatures, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures{instance=\"$host\",sensor=~\"Temp_CPU[0-9]+\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "GPGPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures{instance=\"$host\",sensor=~\"Temp_GPGPU[0-9]+\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "RPM" }
   ],
   "targets": [
    {
     "expr": "ipmi_fan_speed{instance=\"$host\"}",
     "legendFormat": "{{ fan }}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures{instance=\"$host\",sensor=~\"Temp_.*DIMM_[A-Z]*\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "All Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ipmi_temperatures{instance=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "All Voltages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ipmi_voltages{instance=\"$host\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  }
 ]
}